Split app into modules
ARK-Builders/ARK-Rate pull request #131
Opened 2024-11-16 04:51 UTC by mdrlzy

### Resources
All resources are located in `:core:presentation`. Keeping resources in feature modules and ensuring that they are not duplicated will be a mess. We can easily access them via type aliases.
```
CoreR.kt

typealias CoreRString = R.string
typealias CoreRDrawable = R.drawable
```
### Navigation
Feature modules generate compose-destination classes. We collect them in app module and create a single graph manually.
`compose-destinations` library works in destinations mode
```
ksp {
    arg("compose-destinations.mode", "destinations")
}
```
### DI
We have `CoreComponent` in `:core:di` that contains common dependencies with `Singleton` scope. Feature modules create own components that depend on `CoreComponent` with own scopes. App holds `CoreComponent` and provides it. 

Feature component are stored in separate object called `FeatureComponentHolder` inside the module. This is the easiest way to reuse component between compose screens in module.

### Notes

- `:core:di` and `:core:db` needed to not expose `:core:data` module and implementation so feature modules only know about `:core:domain` and interfaces
- Build config replaced with `BuildConfigFields` and `BuildConfigFieldsProvider`. `BuildConfigFieldsProvider` created in `:core:data` module and initialized in app module. So all modules can use the build config of app module.

2024-11-27 19:34 UTC, shubertm requested changes

2024-11-28 12:58 UTC, mdrlzy commented on core/data/src/main/java/dev/arkbuilders/rate/core/data/repo/TimestampRepoImpl.kt
> +    override suspend fun getTimestamp(type: TimestampType) =
Can you give an argument? Other modules use `TimestampRepo` where return types are specified and don't know about `TimestampRepoImpl`. Also this is allowed by ktlint.

2024-11-28 12:59 UTC, mdrlzy commented on core/data/src/main/java/dev/arkbuilders/rate/core/data/repo/TimestampRepoImpl.kt
> +    override suspend fun rememberTimestamp(type: TimestampType) =
Same as `getTimestamp`

2024-11-28 13:01 UTC, mdrlzy commented on core/presentation/src/main/java/dev/arkbuilders/rate/core/presentation/ui/DropDown.kt
> +                    ArkColor.Border,
I don't see much difference, anyway we will refactor this to use colors from `Theme` to support dark theme

2024-12-03 03:35 UTC, shubertm commented on core/data/src/main/java/dev/arkbuilders/rate/core/data/repo/TimestampRepoImpl.kt
> +    override suspend fun getTimestamp(type: TimestampType) =
Just for convenience, look `rememberTimestamp` returns `Unit` and `getTimestamp` looks like it returns `Unit` as well

2024-12-03 03:35 UTC, shubertm commented on core/presentation/src/main/java/dev/arkbuilders/rate/core/presentation/ui/DropDown.kt
> +                    ArkColor.Border,
Alright, cool

2024-12-03 13:21 UTC, shubertm commented
https://github.com/user-attachments/assets/9447f6c7-09aa-43bd-b096-344ee3b635c9

- [ ] Trying to change the "from currency" creates new "to currency"

2024-12-13 19:12 UTC, shubertm approved these changes

2024-12-14 01:53 UTC, merged